### ISSUE TITLE
`system(3)` support

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/libiosexec#1]
Adding a `system(3)` alternative would be incredibly useful for a couple of my ports of BSD tools.

**Comment by Diatrus** [comment]
@CRKatri I'm 70% sure system() doesn't need any help, and instead needs to be made available in the SDK. If you end up testing, please let me know.

**Comment by CRKatri** [comment]
I'll test that out tomorrow.

**Comment by CRKatri** [comment]
I tested it and `system(3)` does work fine once `stdlib.h` is patched.
