### ISSUE TITLE
POSIX semaphore API

### ISSUE THREAD

**Issue by Torrekie** [ProcursusTeam/libiosexec#18]
`sem_init`, `sem_destroy` and `sem_getvalue` that marked as deprecated in `<sys/semaphore.h>` has stub implementations under [xnu/libsyscall/wrappers/posix_sem_obsolete.c](https://github.com/apple-oss-distributions/xnu/blob/main/libsyscall/wrappers/posix_sem_obsolete.c) that always set errno `ENOSYS` and return `-1`. But Apple has been provided alternative sem implementations like `<dispatch/semaphore.h>` and `<mach/semaphore.h>` and they do use them to implement POSIX sem like [this](https://github.com/apple-oss-distributions/text_cmds/blob/4d005540bc9d8222427d46f707d4bf93cbfa0db0/sort/file.c#L135)

libuv also have [implementations](https://github.com/libuv/libuv/blob/3f331e97da5b1cc2e24765dcb6d26c9dd313418f/src/unix/thread.c#L437) for this

**Comment by CRKatri** [comment]
I see no need for us to implement them ourselves. If they've been deprecated since 2013, I doubt much software will use them on Darwin anymore.
