### ISSUE TITLE
Parsing shebang

### ISSUE THREAD

**Issue by Khronos31** [ProcursusTeam/libiosexec#7]
shebang.c
```C
#include <stdio.h>
int main(int argc, char* argv[]){
  for (int i=0;i<argc;i++){
    printf("argv[%d]= %s\n", i, argv[i]);
  }
  return 0;
}
```

test.sh
```bash
#!./shebang a b c "d e"
```

on macOS
```zsh
khronos31@mac tmp % ls         
shebang		shebang.c	test.sh
khronos31@mac tmp % ./test.sh  
argv[0]= ./shebang
argv[1]= a
argv[2]= b
argv[3]= c
argv[4]= "d
argv[5]= e"
argv[6]= ./test.sh
khronos31@mac tmp % 
```

on older versions of jailbroken iOS (without libiosexec)
```bash
iPhone61:~/src/tmp mobile$ ls
shebang*  shebang.c  test.sh*
iPhone61:~/src/tmp mobile$ ./test.sh 
argv[0]= ./shebang
argv[1]= a
argv[2]= b
argv[3]= c
argv[4]= "d
argv[5]= e"
argv[6]= ./test.sh
iPhone61:~/src/tmp mobile$
```

on jailbroken iOS (with libiosexec)
```zsh
iPhone101:~/src/tmp mobile% ls       
shebang*  shebang.c  test.sh*
iPhone101:~/src/tmp mobile% ./test.sh
argv[0]= ./shebang
argv[1]= a b c "d e"
argv[2]= ./test.sh
iPhone101:~/src/tmp mobile%
```

on Linux
```bash
khronos31@Ubuntu:~/src/tmp$ ls
shebang  shebang.c test.sh
khronos31@Ubuntu:~/src/tmp$ ./test.sh 
argv[0]= ./shebang
argv[1]= a b c "d e"
argv[2]= ./test.sh
khronos31@Ubuntu:~/src/tmp$
```

I think it should be aligned with macOS behavior.

**Comment by asdfugil** [comment]
I think it should be aligned with the Linux behaviour because we are using a GNU userspace

**Comment by Khronos31** [comment]
Many users install GNU tools using Homebrew, etc., but the behavior of shebang differs depending on the OS, so for example, if you run it on macOS, you will get the result shown earlier.

macOS and iOS are essentially the same thing.

iOS has had that behavior since before script execution was restricted (i.e., when libiosexec was not needed).

Therefore, if it is executed on iOS, it should be expected to behave the same as macOS for shebang, even if it is a Linux command suite, and it is natural to think that the wrapper is behaving incorrectly.

**Comment by CRKatri** [comment]
FreeBSD passes the arguments the same as Linux (all in `argv[1]`), ~~which is strange because macOS uses FreeBSD’s `exec.c`.~~

**Comment by CRKatri** [comment]
Also, does it really matter? `#!` is very non portable and acts different on every single system. This site has a chart at the bottom documenting differences between each system’s implementation https://www.in-ulm.de/~mascheck/various/shebang/

**Comment by sunflsks** [comment]
This. libiosexec mimics FreeBSD when it comes to shebang parsing, in that the argument passed to the shebang is treated as a single string, rather than split. Most Unices do this anyway, and macOS (along with a few others) is an outlier. However, shebangs in general are not standardized at all like @CRKatri said, so you should probably use something more high-level (like `env`) to pass arguments instead

**Comment by Khronos31** [comment]
Is it extremely important? The answer is no.

However, libiosexec is "An execv shim that allows executing shell scripts on iOS." It doesn't say anywhere that it makes the shebang behave like Linux.

If shebang is split with whitespace in both older versions of iOS and the latest macOS, it is natural that it would be so in the latest iOS, and I think libiosexec is changing the behavior of shebang without explaining it.

If it's aligned with FreeBSD behavior, how about describing it in the README?

**Comment by sunflsks** [comment]
Again, a shebang is about as non-portable as it gets, so relying on this behavior being consistent is already a mistake. However, I'm not opposed to putting a note in the README that warns unsuspecting developers of the change.

**Comment by Khronos31** [comment]
I agree that even giving multiple arguments to shebang is wrong for portability reasons.

What I find strange is that the original behavior (iOS14 doesn't allow you to run the script in the first place, but I consider it to be the same as the former iOS and macOS behavior) is changed by the wrapper.

**Comment by asdfugil** [comment]
POSIX only requires one argument to be supported. Multiple arguments is undefined.

**Comment by sunflsks** [comment]
POSIX actually doesn't say anything about shebangs other than "If the first line of a file of shell commands starts with the characters `#!`, the results are unspecified". Everything else is up to the implementer.

**Comment by Khronos31** [comment]
POSIX does not specify much about shebang, and some operating systems consider a string between `#!` to a newline as the path to the interpreter.
(I don't know about that ancient OS, though).
